services:
  # Web Service
  - type: web
    name: green-toolkit-backend
    env: python
    region: oregon
    plan: free
    
    # Build Configuration
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    
    # Start Configuration
    startCommand: python run_server.py
    
    # Environment Variables
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        generateValue: true
      - key: ENV
        value: production
    
    # Health check
    healthCheckPath: /api/health
