services:
  # Web Service
  - type: web
    name: green-toolkit-backend
    env: python
    region: oregon
    plan: free
    # Install dependencies
    buildCommand: pip install -r requirements.txt
    startCommand: python run_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
    
    # Health check
    healthCheckPath: /api/health
